// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using slurs2.backend.Data;

#nullable disable

namespace slurs2.backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("slurs2.backend.Models.Player", b =>
                {
                    b.Property<string>("SteamId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Country")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SteamName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("SteamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("slurs2.backend.Models.ProcessedLog", b =>
                {
                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.ToTable("ProcessedLogs");
                });

            modelBuilder.Entity("slurs2.backend.Models.SlurInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerSteamId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SlurCount")
                        .HasColumnType("integer");

                    b.Property<int>("SlurType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.HasIndex("PlayerSteamId");

                    b.ToTable("SlurInstances");
                });

            modelBuilder.Entity("slurs2.backend.Models.SlurInstance", b =>
                {
                    b.HasOne("slurs2.backend.Models.ProcessedLog", "ProcessedLog")
                        .WithMany()
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("slurs2.backend.Models.Player", "Player")
                        .WithMany("SlurInstances")
                        .HasForeignKey("PlayerSteamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("ProcessedLog");
                });

            modelBuilder.Entity("slurs2.backend.Models.Player", b =>
                {
                    b.Navigation("SlurInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
